--Left Join 
SELECT FIRSTNAME, LASTNAME, CITY, STATE
FROM Person P
LEFT JOIN ADDRESS A
ON A.Personid = P.Personid


--Union
SELECT FIRSTNAME, LASTNAME, CITY, STATE
FROM Person P, ADDRESS A
WHERE A.Personid = P.Personid
UNION
SELECT FIRSTNAME, LASTNAME, CITY= NULL, STATE=NULL
FROM Person P
WHERE NOT EXISTS
(SELECT 'found' as f FROM ADDRESS A where A.Personid = P.Personid)
